runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

resources:
  cpu: 2
  memory_gb: 2

runtime_config:
  python_version: 3

env_variables:
    DEV: False

automatic_scaling:
  min_num_instances: 1